### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by olakoziou** [ivmarcos/react-to-pdf#21] opened 2020-05-05 05:07 UTC
I'm trying to implement your tool, but I have problem with downloading pdfs with images (set both as background-image and img). Img is dynamic and set with img={example} Do you have any idea how to fix it?

**Comment by gdcardoso** [comment] 2020-05-05 14:14
I'm also trying to use it with the company's logo image, but I didn't succeed.

**Comment by ivmarcos** [comment] 2020-05-05 17:06
@olakoziou, @gdcardoso, could you create a codesandbox showing the problem?

**Comment by gdcardoso** [comment] 2020-05-05 19:49
@ivmarcos thanks for the feedback, but i found that the problem is when i use an image hosted in digital ocean spaces. Using a google image it worked perfectly.

**Comment by olakoziou** [comment] 2020-05-06 08:43
@ivmarcos yep, as @gdcardoso said. I use firebase and the problem is with link from there, ex https://codesandbox.io/s/relaxed-star-3h7ty?file=/src/App.js

**Comment by zainulabd786** [comment] 2020-06-07 15:38
Did anyone find solution to this problem of displaying images in pdf?

**Comment by vladcom** [comment] 2020-07-06 19:11
@olakoziou Hi there. You could try use svg format for images. Its work for me

**Comment by jcpage02** [comment] 2020-07-31 21:17
I am getting a CORS error when trying to create a pdf form HTML that includes an image that is stored on an S3 bucket.  The image renders just fine in the HTML, but it does not show up on the pdf.  Any ideas?

**Comment by vladcom** [comment] 2020-08-01 10:04
> I am getting a CORS error when trying to create a pdf from HTML that includes an image that is stored on an S3 bucket. The image renders just fine in the HTML, but it does not show up on the pdf. Any ideas?

How you add image in your code? Could you send example?

**Comment by jcpage02** [comment] 2020-08-07 18:26
> > I am getting a CORS error when trying to create a pdf from HTML that includes an image that is stored on an S3 bucket. The image renders just fine in the HTML, but it does not show up on the pdf. Any ideas?
> 
> How you add image in your code? Could you send example?

I am using Leaflet.js and adding the image as a layer of the map with the addLayer() method.

**Comment by ivmarcos** [comment] 2020-09-02 12:43
Have you tried the latest v.0.0.12? If so, please provide a codesandbox or jsfiddle with the issue.

**Comment by ivmarcos** [comment] 2020-09-15 01:00
Closing for now, cors errors with images were fixed in recent releases. Reopen in case the issue still remain.

**Closed by ivmarcos** 2020-09-15 01:00 UTC

**Comment by jals990** [comment] 2021-06-16 21:10
@jcpage02  @zainulabd786 @gdcardoso @olakoziou alternative solution 😅

Use **https://astro-cors-server.herokuapp.com/fetch/** for bypass CORS, example:

<img src="http://yourdomain.com/yourpic.png" />

use:

<img src="**https://astro-cors-server.herokuapp.com/fetch/**http://yourdomain.com/yourpic.png" />
